# This is the workflow to push to CI (Continuous Integration) environment at heroku

name: Deploy to heroku - Develop
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - run: npm ci
      - run: npm run build

  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run test
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage/lcov.info

  sonar:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: coverage
          path: coverage/lcov.info
      - uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  deploy:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          #          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          #          heroku_app_name: 'ci-botaprarodar-api' #Must be unique in Heroku
          #         TESTE - TROCAR DUAS LINHAS ABAIXO PELAS DUAS LINHAS ACIMA APOS NOVEMBRO
          heroku_api_key: ${{secrets.HEROKU_API_DELETAR_APOS_TESTE}}
          heroku_app_name: 'teste-botaprarodar-api' #Must be unique in Heroku
          #
          heroku_email: 'botaprarodar.web@gmail.com'
          checkstring: 'ok'
