# This is the workflow to push to CI (Continuous Integration) environment at heroku

name: Deploy to heroku - Develop
on:
  push:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - run: npm ci

  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - run: npm run test

  deploy:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'ci-botaprarodar-api' #Must be unique in Heroku
          heroku_email: 'botaprarodar.web@gmail.com'
          checkstring: 'ok'
